### ISSUE TITLE
Fix recovery from database

### ISSUE THREAD

**Issue by GustavoYamaguchi** [fogbow/federated-network-service#13]
When FNS uses recovery, there's a strange behavior: orders keep DEACTIVATED state, but READY in cached instance state. This makes orders that were deleted, to be listed again as READY.

**Comment by fubica** [comment]
I've check the code, and the bug is caused by the fact that the recovery procedure reads all orders from the database at starting time. It should recover only orders that are in the fulfilled or failed state.
